# Documentation page information
site_name: SparkFun Home Air User Manual
site_description: The user manual for the Home Air from SparkFun Electronics
site_url: https://docs.sparkfun.com/Home_Air_Quality_Monitor/
site_author: SparkFun Electronics

repo_url: https://github.com/sparkfun/Home_Air_Quality_Monitor.git
repo_name: sparkfun/Home_Air_Quality_Monitor

theme:
  name: material
  # custom_dir: docs/overrides
  # logo: img/Icons/sfe_logo_sm.png
  palette:
    primary: grey
    accent: red
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.annotate


    # Enable "view source" and "edit this page" buttons
    - content.action.edit

    # Enables anchor tracking (updates page url with the section user is on)
    # i.e. https://docs.sparkfun.com/<page link>/#<sub-section>
    - navigation.tracking
    - navigation.tabs.sticky
    
    # Enables tabs for navigating the website
    # - navigation.tabs
    # Keeps tabs visible in the header when scrolling
    #- navigation.tabs.sticky
    
    # Adds pop-up button just below the header (when the user starts to scroll up)
    # Allows users to easily jump to the beginning of the page
    - navigation.top
    
    # Renders path for page navigation at top of the page (makes page navigation more mobile friendly)
    - navigation.path


  # Icon in Browser Tab (must be square img - i.e. 32x32 pixels)
  favicon: img/Icons/sfe_logo_sq.png

  icon:
    repo: fontawesome/brands/github

    # Sets icon for "edit this page" buttons
    edit: material/file-document-edit-outline

    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

plugins:
  - search
  - monorepo

copyright: 
    Copyright 2023 - <a href="https://www.sparkfun.com/" target="_blank" rel="noopener">SparkFun Electronics&#174;<br>
    <a href="https://goo.gl/maps/vkstCpQZW6jZMjzYA" target="_blank" rel="noopener">6333 Dry Creek Parkway, Niwot, Colorado 80503</a>


extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sparkfun

# Configures webpage navigation
nav:
  - Hardware Overview: hardware_overview.md
  - Hardware Assembly: hardware_assembly.md
  - Firmware Overview: firmware_overview.md
  - Reference Documents: reference_documents.md
  - Submit Issues: file_issue.md
  - Contribute: contribute.md
